### ISSUE TITLE
Reconsider search modal toggle command

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [MitchellMarkGeorge/TabButler#15]
Ctrl+shift+S is used in a lot of apps for save/save as. Might be better to choose something that is easy to remember and doesn't conflict with both the browser and the users experience/understanding

**Comment by MitchellMarkGeorge** [comment]
We could use `ctrl/cmd` + `shift` + `space` for the Tab Seach

**Comment by MitchellMarkGeorge** [comment]
My thoughts right now are to use `ctrl/cmd` + `shift` + `space` to toggle the Tab Search and `ctrl/cmd` + `alt/option` + `space` to toggle the Action modal @andrei-g-git  @dylanplayer what do you guys think

**Comment by dylanplayer** [comment]
Using `alt/option` + `space` might conflict with [Raycast](https://www.raycast.com/) if someone is using the default keybinds.

**Comment by MitchellMarkGeorge** [comment]
> Using `alt/option` + `space` might conflict with [Raycast](https://www.raycast.com/) if someone is using the default keybinds. 

From what I understand about chrome/browser commands [(here)](https://developer.chrome.com/docs/extensions/reference/commands/), they should be local to the browser alone. And if it does conflict, the user has the option to change the command. The goal of the command we have in the manifest.json is to basically act as a default for the user.

**Comment by MitchellMarkGeorge** [comment]
There is a chance I am wrong tho, and I would be more than happy to experiment with it.

**Comment by andrei-g-git** [comment]
``` ctrl + alt + a ``` doesn't seem to conflict with chrome, firefox or the big 3 OSs, although I'm not sure how other apps might behave when they are not in focus

https://defkey.com/what-means/ctrl-alt-a

**Comment by MitchellMarkGeorge** [comment]
Unfortunately, Chrome does not allow `ctrl + alt` in their keybindings. For now I implemented `ctrl/shift + shift + space` for Tab search and `alt/option + shift + space` for action search. If you have any spare time, please try them out and see if they produce any conflicts. On the Welcome page on install, I will make sure that the user knows of these shortcuts and give them the option to change them right from there. @andrei-g-git @dylanplayer

**Comment by andrei-g-git** [comment]
Hmm it looks like in chromium, on Windows, ``` alt + space ``` is the combo for opening a context menu on the browser's tab bar / frame. Pressing ``` alt + shift + space ``` also registers as that. I only tested this on Brave but google's docu lists those shortcuts too:

https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=

**Comment by andrei-g-git** [comment]
Hmm it looks like in chromium, on Windows, ``` alt + space ``` is the combo for opening a context menu on the browser's tab bar / frame. Pressing ``` alt + shift + space ``` also registers as that (tested on Brave and Chrome).

https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=

**Comment by MitchellMarkGeorge** [comment]
@andrei-g-git Hmmm I see 😩. Definitely need to see what other one we can use. Should we have a different one for Windows?

**Comment by mohitkyadav** [comment]
I'd recommend using  `Cmd/Ctrl + Shift + Space` (default) for tabs and `Cmd/Ctrl + Shift + /` to toggle the action modal.

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav unfortunately that seems to trigger the help menu item

**Comment by mohitkyadav** [comment]
> @mohitkyadav unfortunately that seems to trigger the help menu item

On my machine I may have remapped it at some point 😅. Users can anyway customise it so, we can leave it as it is until a solid alternative unveils itself.

**Comment by MitchellMarkGeorge** [comment]
Wait @andrei-g-git did you test if the extension works with the current keybindings? If not let's test it out. I think it might be hard to find something that is exactly perfect/unused so If the user wants to change it they can change it to something they are comfortable with on install

**Comment by MitchellMarkGeorge** [comment]
> > @mohitkyadav unfortunately that seems to trigger the help menu item
> 
> On my machine I may have remapped it at some point 😅. Users can anyway customise it so, we can leave it as it is until a solid alternative unveils itself.

Exactly what I was thinking. I will leave this issue open for others to leave suggestions but lets start refocusing on other stuff for the beta. Thanks once again guys 🎖️

**Comment by andrei-g-git** [comment]
@MitchellMarkGeorge yep, I tested it on Chrome, Brave and Firefox, latest versions. On chromium only ``` ctrl + shift + space ``` works on pages loaded after installing the extension, on firefox it doesn't seem to have any affect, while ``` alt + shift + space ``` opens a context menu on all browsers. But like I said, I'm running these on Windows 10

I just found a combo that works on all the browsers I use, but the one for searching tabs is a bit unintuitive, ``` alt+shift+r```. For tab actions ```alt+shift+k``` works across the board.

**Comment by MitchellMarkGeorge** [comment]
> @MitchellMarkGeorge yep, I tested it on Chrome, Brave and Firefox, latest versions. On chromium only `ctrl + shift + space` works on pages loaded after installing the extension, on firefox it doesn't seem to have any affect, while `alt + shift + space` opens a context menu on all browsers. But like I said, I'm running these on Windows 10
> 
> I just found a combo that works on all the browsers I use, but the one for searching tabs is a bit unintuitive, ` alt+shift+r`. For tab actions `alt+shift+k` works across the board.
> 
> edit: lol missed the last comment. Ok moving on to another issue then

@andrei-g-git Thanks for testing this out. I had no idea that on Firefox it doesn't even trigger (although we might be missing some keys in the `manifest.json` that could be causing Firefox to error out). If you would like you can continue looking into this as this is important for the beta. From my understanding when using these keybindings they "should" override the default functionality (unless what is being overridden is very important) so that is why your findings were surprising.

**Comment by MitchellMarkGeorge** [comment]
@andrei-g-git when you were testing on Firefox did you run (these steps)[https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/]?

**Comment by andrei-g-git** [comment]
It does look like there will have to be different keybindings between the OSs. On windows ```alt+shift+r``` for search and ```alt+shift+k``` for tab actions worked on all the browsers I tested on. If you want to test other bindings give me a shout.

**Comment by MitchellMarkGeorge** [comment]
@andrei-g-git Ah this makes more sense. In terms with the extension overriding it, that isn't something we can handle explicitly. The best thing we can do is to encourage users to change it something they want. I'll add this to the welcome screen. In terms of the windows keybindings for the tab actions, we can use the `alt + shift + k` for that. But `ctrl + shift + space` should stay since we know it works.

**Comment by MitchellMarkGeorge** [comment]
@andrei-g-git I was finally able to implement this so feel free to take this for a spin

**Comment by andrei-g-git** [comment]
Tested it, alt+shift+k works on chromium and firefox :+1:. 

Unrelated thing, but something I noticed is that the welcome website's shortcut descriptions are static. Want me to tinker with ```WelcomePage.tsx ``` a bit in TabButlerWebsite and see of I can pull some data from the manifest commands into the html?
