### ISSUE TITLE
Shortcut keys are overriden by Firefox's own shortcuts

### ISSUE THREAD

**Issue by andrei-g-git** [MitchellMarkGeorge/TabButler#20]
## Describe the bug

Pressing Ctrl+Shift+S or Ctrl+Shift+K when browsing in Firefox will trigger the firefox shortcuts eg. Ctrl+Shift+S will activate Firefox's screenshot feature and Ctrl+Shift+K  *usually* opens the web console (when the current tab has a github page it will open gihub's global commands modal). 

## Steps to reproduce

* Open a web page in Firefox
* Press Ctrl+Shift+S
* This will bring up the embedded screenshot tool 
* Open a githib link
* Press Ctrl+Shift+K
* This will bring up githib's global commands popup 
* Open pages from other domains like duckduckgo.com,  reddit.com, wikihow.com, freecodecamp.org
* Press Ctrl+Shift+K
* This will bring up firefox's web console

## Expected behavior

* When pressing Ctrl+Shift+S on any page the TabButler's search modal should open
* When pressing Ctrl+Shift+K on any page the TabButler's actions modal should open

## Browser version 

Firefox 102.0.1 64 bit

**Comment by MitchellMarkGeorge** [comment]
This is related to #15. We will need to define shortcuts that don't conflict and are easy for users to use and remember. In chrome, you are allowed to change the shortcuts.

**Comment by MitchellMarkGeorge** [comment]
Generally, the extension has not been tested on Firefox yet so thanks for getting that rolling!
