### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [MitchellMarkGeorge/TabButler#21]
**Is your feature request related to a problem? Please describe.**
It is pretty clear that while the main project is stable, the code itself needs a bit of refactoring and reorganization. Most of the code itself is in the right place, but things like the content script and the Search component could be written better

**Describe the solution you'd like**
To start, I would like to change the content script into a class with an `attach()` method that is called on the body of the document. The purpose of this would be to encapsulate the functionality in a more presentable way rather than a bunch of functions in a file.

**Additional context**
This itself isn't that much of a priority for the beta, but I believe that with new/more contributors joining in, it might be better if the code is in a more understandable state than it is right now.

**Comment by lodenrogue** [comment]
This is a great idea. Are there tests in place which can prove that existing functionality has not been broken once some refactoring has taken place? If not, that would be the first step.

**Comment by MitchellMarkGeorge** [comment]
> This is a great idea. Are there tests in place which can prove that existing functionality has not been broken once some refactoring has taken place? If not, that would be the first step.

Currently there are no tests in the project right now (my bad) bit it is something would look into into. If you would like, you can start looking at that.

**Comment by mohitkyadav** [comment]
I'd like to contribute on this if no one is already working on this. cc @lodenrogue @MitchellMarkGeorge

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav if @lodenrogue doesn't mind go right ahead. Since this isn't a priority for beta, I would suggest that you develop this on a separate branch alongside main. Fortunately main should stay pretty stable for the next few weeks so you should be good to go 👍

**Comment by lodenrogue** [comment]
Since the first step is adding tests without changing the existing code the tests should be merged incrementally into the main branch. Otherwise, any fixes or changes happening in the rest of the code could make the tests fail and the effort would have been wasted.

**Comment by lodenrogue** [comment]
I don't volunteer for adding tests. I was just giving some guidance on the approach

**Comment by MitchellMarkGeorge** [comment]
> Since the first step is adding tests without changing the existing code the tests should be merged incrementally into the main branch. Otherwise, any fixes or changes happening in the rest of the code could make the tests fail and the effort would have been wasted.

Agreed 👍
