### ISSUE TITLE
Open Download / Extension / Settings /History / Bookmarks does nothing

### ISSUE THREAD

**Issue by forteller** [MitchellMarkGeorge/TabButler#65]
**Describe the bug**
Selecting any of these from the Tab Action modal just closes the modal and otherwise doesn't seem to do anything.

**To Reproduce**

1. Press Shift + Alt + K to open the modal
3. Select any of the mentioned actions and press enter

**Expected behavior**
Something should open

**Platform Info (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Firefox
- Version 102.0.1 (flatpak)

Thanks! :)

**Comment by MitchellMarkGeorge** [comment]
@forteller Thanks for finding this bug. When I initially started work on this extension, I was only developing it for Chromium-based browsers. Because of that, when you try to execute those actions on Firefox, the extension would try and open a URL it has no access to. To fix this we'll need to conditional shoe the Firefox equivalent URLs.

**Comment by MitchellMarkGeorge** [comment]
If you would like you can create a PR to fix this bug 👍

**Comment by forteller** [comment]
I see. I don't know how to code, unfortunately, but here's the info I can find:

Download: Does not have a URL AFAIK, but opens in a separate window when pressing Ctrl + Shift + Y
Extension: Does this mean the list of installed extensions? If so it's about:addons
Settings: about:preferences
History: This can be opened in a sidebar (Ctrl+H) or a separate window (Ctrl + Shift + H)
Bookmarks: Sidebar (Ctrl + B) or Bookmarks toolbar (Ctrl + Shift + B) or separate window (Ctrl + Shift + O)

**Comment by MitchellMarkGeorge** [comment]
Ahh I see. Thanks for letting me know! I'll take your suggestions into consideration 🎖️

**Comment by forteller** [comment]
Until you're able to fix this I'd rather remove it from the Firefox version, to not create confusion. Personally I don't really see the use for this at all, so I wouldn't mind just removing it permanently, but at the same time feature parity for both browsers is really important, and I'm sure you had your reason for adding this in the first place :)

**Comment by MitchellMarkGeorge** [comment]
Yea a lot of the current actions themselves are going to be revamped, and part of our plan for the full release is to be able to search through your history/bookmarks right from the Search Modal.

**Comment by MitchellMarkGeorge** [comment]
Based on this bug and with #36 being developed, the best course of action would be to remove those actions.

**Comment by MitchellMarkGeorge** [comment]
<img width="878" alt="Screen Shot 2022-08-10 at 11 01 50 PM" src="https://user-images.githubusercontent.com/49462407/184058144-3efa61bc-74dd-4fe8-9fb6-b0fc1f9a68bd.png">

Even trying to open the extension and setting URLs proved difficult 🤦 . I'll just remove them.
