### ISSUE TITLE
Decouple size from page zoom

### ISSUE THREAD

**Issue by forteller** [MitchellMarkGeorge/TabButler#67]
**Is your feature request related to a problem? Please describe.**
I often have different zoom level on different tabs, according to which level makes the text on that page comfortable for me to read. Some times I zoom in a lot. Then it's quite jarring to open Tab Butler and having it huge on one tab and small on another. I'd like it to be consistent across all tabs.

**Describe the solution you'd like**
The zoom level on a tab should not influence the size of the butler. The size should rather be independent of anything else and possible to change in the settings.

**Describe alternatives you've considered**
The size could be linked to the size of the browsers chrome/interface, if possible.

**Additional context**
Using Firefox

Thanks!

**Comment by MitchellMarkGeorge** [comment]
Thanks for submitting this issue. Unfortunately, this might not be entirely possible as zoom settings depend greatly on the settings set by the browser and the website that we inject the Tab Butler modal into, and it is better not to mess with any of those. I will continue searching for a potential solution but for now, this won't be worked on.
