### ISSUE TITLE
Work on landing page

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [MitchellMarkGeorge/TabButler#7]
Website to link users to closed beta and explain the extension
https://github.com/MitchellMarkGeorge/TabButlerWebsite

**Comment by MitchellMarkGeorge** [comment]
Will probably just use plain html and css

**Comment by mohitkyadav** [comment]
@MitchellMarkGeorge I don't know why you changed the issue from chakra UI to html css 😅 . But I can contribute to the site and rewrite it with react and Chakra ui. Honestly I find this project really interesting and have some suggestions.

Also the launch date, is Aug 1 fixed or can you adjust that?

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav I changed it to simple HTML and CSS cause I thought it would be overkill for a simple landing page website. There is a version of if live [here](https://tabbutler.netlify.app/) if you want to check it out. I am definitely not the best at design and CSS so if you have any improvements you would like to make go right ahead (like responsiveness).

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav In terms of the beta launch date, I wouldn't say it's cast in stone, but I definitely think it's possible to reach. The extension is in a pretty stable state right now and now it's really just looking for bugs and som UI fixes.
