### ISSUE TITLE
Filter based on TabData properties like muted, audible, pinned etc

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [MitchellMarkGeorge/TabButler#70]
**Is your feature request related to a problem? Please describe.**
The purpose of this feature would be to allow users to fund tabs based on a certain property. For example, if a user wants to find all the tabs that are playing audio, they should type ":audible" in the search input to get their result.

**Additional context**
This is defiantly not a priority and is more of an idea than an actually planned feature.

**Comment by forteller** [comment]
Cool idea! Another property that would be nice is every tab that has a video, or has something that potentially can make sound, no matter if it's currently playing or not :)
