### ISSUE TITLE
Create welcome page

### ISSUE THREAD

**Issue by MitchellMarkGeorge** [MitchellMarkGeorge/TabButler#9]
This is a page that is shown on install. This page should show users the shortcuts to trigger search and link to page to change them

**Comment by MitchellMarkGeorge** [comment]
Need to figure out if this should be bundled with the extension or should be hosted somewhere else

**Comment by andrei-g-git** [comment]
Could an options page that also lists the shortcuts on it's top side work? If you only have a few key combos and don't end up needing a large options UI they might fit cohesively on the same page.

**Comment by MitchellMarkGeorge** [comment]
@andrei-g-git sorry I did't see this before but I just implemented this if you want to take a look. I added the same welcome page as the options page of the extension and I has the commands on them so you use case might be handled. Nice thinking! 🎖️
<img width="1117" alt="Screen Shot 2022-07-09 at 11 31 30 PM" src="https://user-images.githubusercontent.com/49462407/178130163-157484d9-c03b-43d4-9a35-235053a4faf0.png">

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav We might need to make this in line with the look of the website... How do you feel about taking this on?

**Comment by mohitkyadav** [comment]
@MitchellMarkGeorge this welcome page, can it be hosted on a remote url, let's say `https://tabbutler.netlify.app/<some_path>`?

Or is it strictly required from chrome extension side to be a static html page?

**Comment by MitchellMarkGeorge** [comment]
@mohitkyadav I initally thought is should only be local but using a remote url should be fine 👍
